= Sage905
:page-layout: author
:page-feature_image: feature-wolf
:page-square_related: recommend-wolf
:page-author_avatar: sage
:page-author_name: Sage905
:page-permalink: /author/sage905
:page-desc: Who are you?

## About Patrick Toal (aka Sage905)

Considered wise by some, and a wise-ass by others, he was given the online
handle "The Sage" by a childhood friend, back in the days when BBS'
footnote:[https://en.wikipedia.org/wiki/Bulletin_board_system[Wikipedia entry
on BBS's] for those who are not digital dinosaurs]
were all the rage.  This is a reference to a character in the most awesome of
comic books, http://groo.com/[Groo the Wanderer] by the talented Sergio Aragonés.
(Iron Man may be cooler, but Groo brings more laughs). "905" is an
anachronism used by old BBS'ers to uniquely identify themselves.  It is merely
the telephone area code he lived in at the time.

Patrick has been involved with Internet technologies in one form or another since
the mid 90's.  During the early part of the 90's, he was employed by a local
computer shop called "Rentronics", where he met a colleague who was a student at
McMaster University.  This fellow shared his McMaster user account with Patrick,
for which he will be forever grateful. This was his door to the Internet,
which would forever change the course of Patrick's life.

The Internet allowed Patrick to learn the basics about Unix and shortly thereafter
he discovered Linux.  Countless hours were spent installing, compiling, formatting
and starting over again.  All the while, new skills were being developed that
would open even more doors in the future.

The Hamilton-Wentworth Freenet was a project which made Internet access and
community information freely available to people from all walks of life.
As a volunteer and later a staff member, he helped design, build and operate the
service, and was able to work with many very bright people who freely shared their
knowledge with him.  This gave him connections to a couple of people who opened
the next door in his career.

At the dawn of the Broadband Access era, he was fortunate to be hired by a
forward-looking cable company when Cable Modem technology was in infancy.
Over the course of 5 years, Patrick was the Server and Network Administrator,
responsible for everything from Server and Router installation and operation to
software development, Tier 3 support, and on-site installer.  After 5 years,
the company attracted the attentions of a wealthy suitor, and the cable assets
were sold off.  It was time to look for a new path.

Thanks to connections made at the cable company, Patrick was able to get an
interview (well, five, actually) at Cisco, the juggernaut of the Internet at
that time.  This new opportunity turned into a 16 year career of helping
customers design, deploy and operate massive networks to provide Internet
access to Canadians.  He worked on a countless number of amazing projects involving
Network Design, Cable Access, UI/UX Development, Server Automation and dozens of
other technologies involving industry buzzwords.  It was a truly amazing time,
working with amazing people.

Patrick is preparing to start a new chapter in his life, and perhaps this blog
will become part of it.  There's an equally good chance that it will fall into
disuse as he becomes enveloped by whatever the future holds.  Either way,
he's looking forward to some exciting times.

